#!/usr/bin/env bash
# =====================================================================================
# T17-S1 — cross-compile arti-mobile to arm64-v8a + armeabi-v7a .so via cargo-ndk.
# =====================================================================================
# ⚠ THIS HAS NOT BEEN RUN. The spike host has NO Rust toolchain and NO Android NDK, so this script
# is the DOCUMENTED recipe, not a verified build. Run it on a machine with the toolchain below; it
# is written to fail loudly (set -euo pipefail) rather than half-produce a .so.
#
# Prerequisites (record exact versions in README.md after a real run):
#   * rustup + a stable Rust (>= the arti MSRV; check arti-client's Cargo.toml `rust-version`).
#   * rustup targets: aarch64-linux-android, armv7-linux-androideabi
#       rustup target add aarch64-linux-android armv7-linux-androideabi
#   * Android NDK (r26+); export ANDROID_NDK_HOME=/path/to/ndk/<version>
#   * cargo-ndk:  cargo install cargo-ndk
#   * llvm-strip from the NDK (cargo-ndk finds it; we also strip via the release profile).
# =====================================================================================
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

: "${ANDROID_NDK_HOME:?set ANDROID_NDK_HOME to your Android NDK (r26+) before building}"

# Output straight into the app's jniLibs so gradle packages libarti_mobile.so per ABI.
# NOTE (T17-S2): this is the SPIKE drop site; a shipping cutover would gate it behind the flag build.
JNILIBS="$HERE/../android/app/src/main/jniLibs"
mkdir -p "$JNILIBS"

echo ">> cargo-ndk build (release, arm64-v8a + armeabi-v7a)…"
# cargo-ndk maps Android ABI names to the rustc targets and sets the NDK linker/sysroot.
cargo ndk \
  -t arm64-v8a \
  -t armeabi-v7a \
  -o "$JNILIBS" \
  build --release

echo ">> stripping + sizing…"
# The release profile already sets strip=true; run llvm-strip as a backstop and record sizes.
SIZE_REPORT="$HERE/SIZE_REPORT.md"
{
  echo "# Arti .so size report (T17-S1)"
  echo
  echo "Generated by build.sh on: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  echo "| ABI | libarti_mobile.so (stripped bytes) |"
  echo "|---|---|"
} > "$SIZE_REPORT"

STRIP="$(find "$ANDROID_NDK_HOME" -name 'llvm-strip' -type f | head -n1 || true)"
for abi in arm64-v8a armeabi-v7a; do
  so="$JNILIBS/$abi/libarti_mobile.so"
  if [[ -f "$so" ]]; then
    [[ -n "$STRIP" ]] && "$STRIP" --strip-unneeded "$so" || true
    bytes="$(wc -c < "$so" | tr -d ' ')"
    echo "| $abi | $bytes |" >> "$SIZE_REPORT"
    echo "   $abi: $bytes bytes  ($so)"
  else
    echo "| $abi | MISSING (build produced no .so) |" >> "$SIZE_REPORT"
    echo "   !! $abi: MISSING — build did not emit $so"
  fi
done

cat >> "$SIZE_REPORT" <<'EOF'

## Incumbent baseline to compare against (measure on the SAME device build)

The C-tor path bundles, per ABI:
  * libtor.so                      (info.guardianproject:tor-android:0.4.8.22)
  * IPtProxy's gomobile .so        (com.netzarchitekten:IPtProxy:5.5.0 — lyrebird/obfs4+snowflake+webtunnel, in-process)
  * libcrypto.so / libssl.so       (OpenSSL; shared via pickFirst with op-sqlite's SQLCipher)

To get the true delta, unzip both per-ABI APKs and compare lib/<abi> total bytes:
  unzip -l app-arm64-v8a-debug.apk | grep 'lib/arm64-v8a/'
Record: incumbent lib/<abi> total, Arti lib/<abi> total (libarti_mobile.so + any rustls/ring deps),
and the resulting APK-DOWNLOAD delta (the sideload-over-Tor cost build.gradle legacy-packaging minimizes).
EOF

echo ">> wrote $SIZE_REPORT"
echo ">> NOTE: a host-target smoke (direct TorClient → known .onion) should pass BEFORE trusting these libs:"
echo "        cargo test --release -- --ignored connect_direct_onion   # network-gated"
