#!/usr/bin/env bash
# =====================================================================================
# Cross-compile arti-mobile to arm64-v8a + armeabi-v7a .so for the Android app.
# =====================================================================================
# ── STATUS 2026-07-27 (Windows host) ────────────────────────────────────────────────────────────
# WORKS. `cargo check`/`cargo build --target aarch64-linux-android` complete with 0 errors for the
# whole 519-crate arti graph. Cargo.lock is committed and pins that graph.
#
# TWO HOST QUIRKS THIS SCRIPT WORKS AROUND — both cost hours to rediscover:
#
#   1. cargo-ndk will NOT install here: building its `windows-sys` dependency dies with
#      "error calling dlltool 'dlltool.exe': program not found". So this script does what cargo-ndk
#      would have done — set the per-target linker/CC/AR/RANLIB env vars directly. That is the whole
#      of cargo-ndk's job for our purposes.
#
#   2. There is NO host C compiler, so a HOST build (`cargo check` with no --target, and therefore
#      `cargo test`) CANNOT work: `ring`'s build script compiles C. The MinGW gcc bundled with the
#      rust-mingw component is link-only and says so in its own GCC-WARNING.txt — it fails with
#      "cannot execute 'cc1'". Cross-compiling is fine because only build scripts run on the host,
#      and those are pure Rust.
#      ⇒ To RUN the unit tests, cross-compile them and execute on a device:
#           cargo test --target aarch64-linux-android --no-run
#           adb push <test-binary> /data/local/tmp/ && adb shell /data/local/tmp/<name>
#        (/data/local/tmp is exec-able for the shell user; app-data dirs are not.)
# ────────────────────────────────────────────────────────────────────────────────────────────────
#
# Prerequisites:
#   * rustup + stable Rust. On this host: stable-x86_64-pc-windows-gnu (the MSVC toolchain has no
#     linker here, and under Git Bash rustc picks up MSYS's /usr/bin/link coreutil instead).
#   * rustup targets: aarch64-linux-android, armv7-linux-androideabi
#       rustup target add aarch64-linux-android armv7-linux-androideabi
#   * Android NDK (r26+); export ANDROID_NDK_HOME=/path/to/ndk/<version>
# =====================================================================================
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

: "${ANDROID_NDK_HOME:?set ANDROID_NDK_HOME to your Android NDK (r26+) before building}"

NDK_BIN="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/windows-x86_64/bin"
[[ -d "$NDK_BIN" ]] || NDK_BIN="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
CLANG_EXT=""
[[ -f "$NDK_BIN/aarch64-linux-android21-clang.cmd" ]] && CLANG_EXT=".cmd"

# Output straight into the app's jniLibs so gradle packages libarti_mobile.so per ABI.
JNILIBS="$HERE/../android/app/src/arti/jniLibs"
mkdir -p "$JNILIBS/arm64-v8a" "$JNILIBS/armeabi-v7a"

# minSdk is 24 (android/build.gradle), so the API-21 clang wrappers are fine.
build_abi() {
  local abi="$1" target="$2" clang="$3" envkey="$4"
  echo ">> $abi ($target)…"
  env \
    "CARGO_TARGET_${envkey^^}_LINKER=$NDK_BIN/$clang$CLANG_EXT" \
    "CC_$envkey=$NDK_BIN/$clang$CLANG_EXT" \
    "AR_$envkey=$NDK_BIN/llvm-ar" \
    "RANLIB_$envkey=$NDK_BIN/llvm-ranlib" \
    cargo build --release --target "$target"
  cp "target/$target/release/libarti_mobile.so" "$JNILIBS/$abi/libarti_mobile.so"
}

build_abi arm64-v8a   aarch64-linux-android  aarch64-linux-android21-clang  aarch64_linux_android
build_abi armeabi-v7a armv7-linux-androideabi armv7a-linux-androideabi21-clang armv7_linux_androideabi

echo ">> stripping + sizing…"
# The release profile already sets strip=true; run llvm-strip as a backstop and record sizes.
SIZE_REPORT="$HERE/SIZE_REPORT.md"
{
  echo "# Arti .so size report (T17-S1)"
  echo
  echo "Generated by build.sh on: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  echo "| ABI | libarti_mobile.so (stripped bytes) |"
  echo "|---|---|"
} > "$SIZE_REPORT"

STRIP="$(find "$ANDROID_NDK_HOME" -name 'llvm-strip' -type f | head -n1 || true)"
for abi in arm64-v8a armeabi-v7a; do
  so="$JNILIBS/$abi/libarti_mobile.so"
  if [[ -f "$so" ]]; then
    [[ -n "$STRIP" ]] && "$STRIP" --strip-unneeded "$so" || true
    bytes="$(wc -c < "$so" | tr -d ' ')"
    echo "| $abi | $bytes |" >> "$SIZE_REPORT"
    echo "   $abi: $bytes bytes  ($so)"
  else
    echo "| $abi | MISSING (build produced no .so) |" >> "$SIZE_REPORT"
    echo "   !! $abi: MISSING — build did not emit $so"
  fi
done

cat >> "$SIZE_REPORT" <<'EOF'

## Historical: the arti-client 0.28.0 → 0.44.0 bump (Arti 1.4.1 → 2.5.0), 2026-07-27

Measured bytes, same host, same profile, same NDK — each figure read with `wc -c` off the stripped
`.so` that landed in `jniLibs/`, never off a timestamp (`libarti_mobile.so` is gitignored for BOTH
ABIs, so a stale build is invisible in a `git diff` and byte comparison is the only honest check):

| ABI | 0.28.0 | 0.44.0, features unchanged | 0.44.0 + flowctl-cc + CGO (shipped) | net delta |
|---|---|---|---|---|
| arm64-v8a   | 5,941,576 | 6,154,616 | 6,181,216 | +239,640 (+4.03%) |
| armeabi-v7a | 4,150,976 | 4,539,436 | 4,559,476 | +408,500 (+9.84%) |

The middle column isolates the two effects: ~15 months of upstream growth accounts for almost all
of it, while enabling congestion control and Counter Galois Onion costs only 26,600 B (arm64) /
20,040 B (armv7) — about 0.4% — because both are pure Rust (`aes`/`ctr`/`polyval`) and reuse
crypto primitives already in the graph. That is the whole performance rationale for the bump for
under half a percent of size. Do not "save" it by dropping those two features; see Cargo.toml for
why they are NOT on by default in a `default-features = false` build.

## Incumbent baseline to compare against (measure on the SAME device build)

The C-tor path bundles, per ABI:
  * libtor.so                      (info.guardianproject:tor-android:0.4.8.22)
  * IPtProxy's gomobile .so        (com.netzarchitekten:IPtProxy:5.5.0 — lyrebird/obfs4+snowflake+webtunnel, in-process)
  * libcrypto.so / libssl.so       (OpenSSL; shared via pickFirst with op-sqlite's SQLCipher)

To get the true delta, unzip both per-ABI APKs and compare lib/<abi> total bytes:
  unzip -l app-arm64-v8a-debug.apk | grep 'lib/arm64-v8a/'
Record: incumbent lib/<abi> total, Arti lib/<abi> total (libarti_mobile.so + any rustls/ring deps),
and the resulting APK-DOWNLOAD delta (the sideload-over-Tor cost build.gradle legacy-packaging minimizes).
EOF

echo ">> wrote $SIZE_REPORT"
echo ">> NOTE: a host-target smoke (direct TorClient → known .onion) should pass BEFORE trusting these libs:"
echo "        cargo test --release -- --ignored connect_direct_onion   # network-gated"
